{ url: 'https://api.github.com/repos/ricoh/si-apps/pulls/484',
  id: 88191505,
  html_url: 'https://github.com/ricoh/si-apps/pull/484',
  diff_url: 'https://github.com/ricoh/si-apps/pull/484.diff',
  patch_url: 'https://github.com/ricoh/si-apps/pull/484.patch',
  issue_url: 'https://api.github.com/repos/ricoh/si-apps/issues/484',
  number: 484,
  state: 'open',
  locked: false,
  title: '[modify] apiInit at index.html',
  user:
   { login: 'MasafumiTokiwa',
     id: 9333050,
     avatar_url: 'https://avatars.githubusercontent.com/u/9333050?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/MasafumiTokiwa',
     html_url: 'https://github.com/MasafumiTokiwa',
     followers_url: 'https://api.github.com/users/MasafumiTokiwa/followers',
     following_url: 'https://api.github.com/users/MasafumiTokiwa/following{/other_user}',
     gists_url: 'https://api.github.com/users/MasafumiTokiwa/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/MasafumiTokiwa/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/MasafumiTokiwa/subscriptions',
     organizations_url: 'https://api.github.com/users/MasafumiTokiwa/orgs',
     repos_url: 'https://api.github.com/users/MasafumiTokiwa/repos',
     events_url: 'https://api.github.com/users/MasafumiTokiwa/events{/privacy}',
     received_events_url: 'https://api.github.com/users/MasafumiTokiwa/received_events',
     type: 'User',
     site_admin: false },
  body: '* ホームでapi-endpointを取得しにいってなかったので修正\r\n * 通常使いだと起きないが、ローカルのgulpにMFPからアクセスするときにapi-endpointもローカルストレージに入れないといけなかったので修正',
  created_at: '2016-10-06T02:57:11Z',
  updated_at: '2016-10-06T07:48:15Z',
  closed_at: null,
  merged_at: null,
  merge_commit_sha: 'e8f8ce4ffc8ad856f0d70968fe1544509195ea67',
  assignee:
   { login: 'hashikami',
     id: 3213880,
     avatar_url: 'https://avatars.githubusercontent.com/u/3213880?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/hashikami',
     html_url: 'https://github.com/hashikami',
     followers_url: 'https://api.github.com/users/hashikami/followers',
     following_url: 'https://api.github.com/users/hashikami/following{/other_user}',
     gists_url: 'https://api.github.com/users/hashikami/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/hashikami/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/hashikami/subscriptions',
     organizations_url: 'https://api.github.com/users/hashikami/orgs',
     repos_url: 'https://api.github.com/users/hashikami/repos',
     events_url: 'https://api.github.com/users/hashikami/events{/privacy}',
     received_events_url: 'https://api.github.com/users/hashikami/received_events',
     type: 'User',
     site_admin: false },
  assignees:
   [ { login: 'hashikami',
       id: 3213880,
       avatar_url: 'https://avatars.githubusercontent.com/u/3213880?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/hashikami',
       html_url: 'https://github.com/hashikami',
       followers_url: 'https://api.github.com/users/hashikami/followers',
       following_url: 'https://api.github.com/users/hashikami/following{/other_user}',
       gists_url: 'https://api.github.com/users/hashikami/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/hashikami/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/hashikami/subscriptions',
       organizations_url: 'https://api.github.com/users/hashikami/orgs',
       repos_url: 'https://api.github.com/users/hashikami/repos',
       events_url: 'https://api.github.com/users/hashikami/events{/privacy}',
       received_events_url: 'https://api.github.com/users/hashikami/received_events',
       type: 'User',
       site_admin: false },
     { login: 'naoki-tomita',
       id: 6903308,
       avatar_url: 'https://avatars.githubusercontent.com/u/6903308?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/naoki-tomita',
       html_url: 'https://github.com/naoki-tomita',
       followers_url: 'https://api.github.com/users/naoki-tomita/followers',
       following_url: 'https://api.github.com/users/naoki-tomita/following{/other_user}',
       gists_url: 'https://api.github.com/users/naoki-tomita/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/naoki-tomita/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/naoki-tomita/subscriptions',
       organizations_url: 'https://api.github.com/users/naoki-tomita/orgs',
       repos_url: 'https://api.github.com/users/naoki-tomita/repos',
       events_url: 'https://api.github.com/users/naoki-tomita/events{/privacy}',
       received_events_url: 'https://api.github.com/users/naoki-tomita/received_events',
       type: 'User',
       site_admin: false },
     { login: 'watanabet-87',
       id: 10125944,
       avatar_url: 'https://avatars.githubusercontent.com/u/10125944?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/watanabet-87',
       html_url: 'https://github.com/watanabet-87',
       followers_url: 'https://api.github.com/users/watanabet-87/followers',
       following_url: 'https://api.github.com/users/watanabet-87/following{/other_user}',
       gists_url: 'https://api.github.com/users/watanabet-87/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/watanabet-87/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/watanabet-87/subscriptions',
       organizations_url: 'https://api.github.com/users/watanabet-87/orgs',
       repos_url: 'https://api.github.com/users/watanabet-87/repos',
       events_url: 'https://api.github.com/users/watanabet-87/events{/privacy}',
       received_events_url: 'https://api.github.com/users/watanabet-87/received_events',
       type: 'User',
       site_admin: false } ],
  milestone:
   { url: 'https://api.github.com/repos/ricoh/si-apps/milestones/1',
     html_url: 'https://github.com/ricoh/si-apps/milestones/10%E6%9C%8811%E6%97%A5%E5%90%91%E3%81%91%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9',
     labels_url: 'https://api.github.com/repos/ricoh/si-apps/milestones/1/labels',
     id: 2051098,
     number: 1,
     title: '10月11日向けリリース',
     description: '',
     creator:
      { login: 'MasafumiTokiwa',
        id: 9333050,
        avatar_url: 'https://avatars.githubusercontent.com/u/9333050?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/MasafumiTokiwa',
        html_url: 'https://github.com/MasafumiTokiwa',
        followers_url: 'https://api.github.com/users/MasafumiTokiwa/followers',
        following_url: 'https://api.github.com/users/MasafumiTokiwa/following{/other_user}',
        gists_url: 'https://api.github.com/users/MasafumiTokiwa/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/MasafumiTokiwa/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/MasafumiTokiwa/subscriptions',
        organizations_url: 'https://api.github.com/users/MasafumiTokiwa/orgs',
        repos_url: 'https://api.github.com/users/MasafumiTokiwa/repos',
        events_url: 'https://api.github.com/users/MasafumiTokiwa/events{/privacy}',
        received_events_url: 'https://api.github.com/users/MasafumiTokiwa/received_events',
        type: 'User',
        site_admin: false },
     open_issues: 2,
     closed_issues: 5,
     state: 'open',
     created_at: '2016-10-06T02:51:20Z',
     updated_at: '2016-10-07T01:39:14Z',
     due_on: '2016-10-08T00:00:00Z',
     closed_at: null },
  commits_url: 'https://api.github.com/repos/ricoh/si-apps/pulls/484/commits',
  review_comments_url: 'https://api.github.com/repos/ricoh/si-apps/pulls/484/comments',
  review_comment_url: 'https://api.github.com/repos/ricoh/si-apps/pulls/comments{/number}',
  comments_url: 'https://api.github.com/repos/ricoh/si-apps/issues/484/comments',
  statuses_url: 'https://api.github.com/repos/ricoh/si-apps/statuses/0a8c7fb6e940f496e40dd2792999fc538bd0d622',
  head:
   { label: 'ricoh:feature-api-init-app',
     ref: 'feature-api-init-app',
     sha: '0a8c7fb6e940f496e40dd2792999fc538bd0d622',
     user:
      { login: 'ricoh',
        id: 808817,
        avatar_url: 'https://avatars.githubusercontent.com/u/808817?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ricoh',
        html_url: 'https://github.com/ricoh',
        followers_url: 'https://api.github.com/users/ricoh/followers',
        following_url: 'https://api.github.com/users/ricoh/following{/other_user}',
        gists_url: 'https://api.github.com/users/ricoh/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ricoh/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ricoh/subscriptions',
        organizations_url: 'https://api.github.com/users/ricoh/orgs',
        repos_url: 'https://api.github.com/users/ricoh/repos',
        events_url: 'https://api.github.com/users/ricoh/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ricoh/received_events',
        type: 'Organization',
        site_admin: false },
     repo:
      { id: 46472388,
        name: 'si-apps',
        full_name: 'ricoh/si-apps',
        owner: [Object],
        private: true,
        html_url: 'https://github.com/ricoh/si-apps',
        description: 'Web Browser NX Applications in Smart Integration',
        fork: false,
        url: 'https://api.github.com/repos/ricoh/si-apps',
        forks_url: 'https://api.github.com/repos/ricoh/si-apps/forks',
        keys_url: 'https://api.github.com/repos/ricoh/si-apps/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/ricoh/si-apps/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/ricoh/si-apps/teams',
        hooks_url: 'https://api.github.com/repos/ricoh/si-apps/hooks',
        issue_events_url: 'https://api.github.com/repos/ricoh/si-apps/issues/events{/number}',
        events_url: 'https://api.github.com/repos/ricoh/si-apps/events',
        assignees_url: 'https://api.github.com/repos/ricoh/si-apps/assignees{/user}',
        branches_url: 'https://api.github.com/repos/ricoh/si-apps/branches{/branch}',
        tags_url: 'https://api.github.com/repos/ricoh/si-apps/tags',
        blobs_url: 'https://api.github.com/repos/ricoh/si-apps/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/ricoh/si-apps/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/ricoh/si-apps/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/ricoh/si-apps/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/ricoh/si-apps/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/ricoh/si-apps/languages',
        stargazers_url: 'https://api.github.com/repos/ricoh/si-apps/stargazers',
        contributors_url: 'https://api.github.com/repos/ricoh/si-apps/contributors',
        subscribers_url: 'https://api.github.com/repos/ricoh/si-apps/subscribers',
        subscription_url: 'https://api.github.com/repos/ricoh/si-apps/subscription',
        commits_url: 'https://api.github.com/repos/ricoh/si-apps/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/ricoh/si-apps/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/ricoh/si-apps/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/ricoh/si-apps/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/ricoh/si-apps/contents/{+path}',
        compare_url: 'https://api.github.com/repos/ricoh/si-apps/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/ricoh/si-apps/merges',
        archive_url: 'https://api.github.com/repos/ricoh/si-apps/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/ricoh/si-apps/downloads',
        issues_url: 'https://api.github.com/repos/ricoh/si-apps/issues{/number}',
        pulls_url: 'https://api.github.com/repos/ricoh/si-apps/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/ricoh/si-apps/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/ricoh/si-apps/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/ricoh/si-apps/labels{/name}',
        releases_url: 'https://api.github.com/repos/ricoh/si-apps/releases{/id}',
        deployments_url: 'https://api.github.com/repos/ricoh/si-apps/deployments',
        created_at: '2015-11-19T06:26:32Z',
        updated_at: '2016-01-14T04:56:22Z',
        pushed_at: '2016-10-07T01:48:59Z',
        git_url: 'git://github.com/ricoh/si-apps.git',
        ssh_url: 'git@github.com:ricoh/si-apps.git',
        clone_url: 'https://github.com/ricoh/si-apps.git',
        svn_url: 'https://github.com/ricoh/si-apps',
        homepage: '',
        size: 5950,
        stargazers_count: 1,
        watchers_count: 1,
        language: 'JavaScript',
        has_issues: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        open_issues_count: 3,
        forks: 0,
        open_issues: 3,
        watchers: 1,
        default_branch: 'master' } },
  base:
   { label: 'ricoh:master',
     ref: 'master',
     sha: 'c100da923ed599f4f5ecc86e24e20dc15f1fa4df',
     user:
      { login: 'ricoh',
        id: 808817,
        avatar_url: 'https://avatars.githubusercontent.com/u/808817?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/ricoh',
        html_url: 'https://github.com/ricoh',
        followers_url: 'https://api.github.com/users/ricoh/followers',
        following_url: 'https://api.github.com/users/ricoh/following{/other_user}',
        gists_url: 'https://api.github.com/users/ricoh/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/ricoh/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/ricoh/subscriptions',
        organizations_url: 'https://api.github.com/users/ricoh/orgs',
        repos_url: 'https://api.github.com/users/ricoh/repos',
        events_url: 'https://api.github.com/users/ricoh/events{/privacy}',
        received_events_url: 'https://api.github.com/users/ricoh/received_events',
        type: 'Organization',
        site_admin: false },
     repo:
      { id: 46472388,
        name: 'si-apps',
        full_name: 'ricoh/si-apps',
        owner: [Object],
        private: true,
        html_url: 'https://github.com/ricoh/si-apps',
        description: 'Web Browser NX Applications in Smart Integration',
        fork: false,
        url: 'https://api.github.com/repos/ricoh/si-apps',
        forks_url: 'https://api.github.com/repos/ricoh/si-apps/forks',
        keys_url: 'https://api.github.com/repos/ricoh/si-apps/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/ricoh/si-apps/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/ricoh/si-apps/teams',
        hooks_url: 'https://api.github.com/repos/ricoh/si-apps/hooks',
        issue_events_url: 'https://api.github.com/repos/ricoh/si-apps/issues/events{/number}',
        events_url: 'https://api.github.com/repos/ricoh/si-apps/events',
        assignees_url: 'https://api.github.com/repos/ricoh/si-apps/assignees{/user}',
        branches_url: 'https://api.github.com/repos/ricoh/si-apps/branches{/branch}',
        tags_url: 'https://api.github.com/repos/ricoh/si-apps/tags',
        blobs_url: 'https://api.github.com/repos/ricoh/si-apps/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/ricoh/si-apps/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/ricoh/si-apps/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/ricoh/si-apps/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/ricoh/si-apps/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/ricoh/si-apps/languages',
        stargazers_url: 'https://api.github.com/repos/ricoh/si-apps/stargazers',
        contributors_url: 'https://api.github.com/repos/ricoh/si-apps/contributors',
        subscribers_url: 'https://api.github.com/repos/ricoh/si-apps/subscribers',
        subscription_url: 'https://api.github.com/repos/ricoh/si-apps/subscription',
        commits_url: 'https://api.github.com/repos/ricoh/si-apps/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/ricoh/si-apps/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/ricoh/si-apps/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/ricoh/si-apps/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/ricoh/si-apps/contents/{+path}',
        compare_url: 'https://api.github.com/repos/ricoh/si-apps/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/ricoh/si-apps/merges',
        archive_url: 'https://api.github.com/repos/ricoh/si-apps/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/ricoh/si-apps/downloads',
        issues_url: 'https://api.github.com/repos/ricoh/si-apps/issues{/number}',
        pulls_url: 'https://api.github.com/repos/ricoh/si-apps/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/ricoh/si-apps/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/ricoh/si-apps/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/ricoh/si-apps/labels{/name}',
        releases_url: 'https://api.github.com/repos/ricoh/si-apps/releases{/id}',
        deployments_url: 'https://api.github.com/repos/ricoh/si-apps/deployments',
        created_at: '2015-11-19T06:26:32Z',
        updated_at: '2016-01-14T04:56:22Z',
        pushed_at: '2016-10-07T01:48:59Z',
        git_url: 'git://github.com/ricoh/si-apps.git',
        ssh_url: 'git@github.com:ricoh/si-apps.git',
        clone_url: 'https://github.com/ricoh/si-apps.git',
        svn_url: 'https://github.com/ricoh/si-apps',
        homepage: '',
        size: 5950,
        stargazers_count: 1,
        watchers_count: 1,
        language: 'JavaScript',
        has_issues: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        open_issues_count: 3,
        forks: 0,
        open_issues: 3,
        watchers: 1,
        default_branch: 'master' } },
  _links:
   { self: { href: 'https://api.github.com/repos/ricoh/si-apps/pulls/484' },
     html: { href: 'https://github.com/ricoh/si-apps/pull/484' },
     issue: { href: 'https://api.github.com/repos/ricoh/si-apps/issues/484' },
     comments: { href: 'https://api.github.com/repos/ricoh/si-apps/issues/484/comments' },
     review_comments: { href: 'https://api.github.com/repos/ricoh/si-apps/pulls/484/comments' },
     review_comment: { href: 'https://api.github.com/repos/ricoh/si-apps/pulls/comments{/number}' },
     commits: { href: 'https://api.github.com/repos/ricoh/si-apps/pulls/484/commits' },
     statuses: { href: 'https://api.github.com/repos/ricoh/si-apps/statuses/0a8c7fb6e940f496e40dd2792999fc538bd0d622' } } }
